### ISSUE TITLE
Use grpc data store from flutter Web

### ISSUE THREAD

**Issue by gedw99** [dint-dev/database#1]
. Can this be supported ?

I am using this from flutter mobile and desktop but need to also call the server from Flutter Web

This example works..

Example of echo service 
https://github.com/sigurdm/grpc_web_flutter_example

Requires envoy running the grpc gateway

**Comment by terrier989** [comment]
Hi!

Thanks for the question. The GRPC adapter is not ready for use yet. It will be documented when it's closer to stable.

We definitely want to support GRPC in browser. My understanding is that:
1.Browser-compatibility without something like Envoy requires avoiding streaming GRPC requests.
2.Accomplishing that is straightforward for simple reads, writes, and searches.
3.It's tricky for transactions because HTTP requests during the transaction are not necessarily received by the same process in the server. But for transactions with limited read isolation requirements and a moderate total size, it should be possible by collecting read results and writes until commit and giving them to the server in a single HTTP request.
